version: '3.7'
services:
  postgres_zabbix:
    image: registry.seduc.ce.gov.br/externos/postgresql_externo:master
    logging:
      driver: loki
      options:
        loki-url: "http://logsexternos.seduc.ce.gov.br:3100/loki/api/v1/push"
        labels: "postgres-zabbix"  
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=0571cb42b6e2ff75ee56a121ff8710a3
    volumes:
      - /srv/postgresql_zabbix:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - net_app
    ports:
      - "5432:5432"
  zabbix_server:
    image: zabbix-server-pgsql:ubuntus-1.0
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro     
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
    env_file:      
      - ./env_vars/.env_srv
    networks:
      - net_app
  zabbix-web-apache-pgsql:
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-5.4-latest
    deploy:
        labels:
        - traefik.frontend.rule=Host:monitoramentodesv.seduc.ce.gov.br
        - traefik.frontend.redirect.entryPoint=https
        - traefik.docker.network=net_app
        - traefik.port=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./env_vars/zabbix.conf.php:/usr/share/zabbix/conf/zabbix.conf.php:ro
      - ./zbx_env/etc/ssl/apache2:/etc/ssl/apache2:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    env_file:
      - ./env_vars/.env_db_pgsql
      - ./env_vars/.env_web 
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    depends_on:
      - postgres_zabbix
    networks:
      - net_app

networks:
  net_app:
    external: true
secrets:
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD



